runtime: nodejs10

handlers:
 - url: /css
   static_dir: dist/css
   secure: always

 - url: /img
   static_dir: dist/img
   secure: always

 - url: /img/icons
   static_dir: dist/img/icons
   secure: always

 - url: /js
   mime_type: text/javascript
   static_dir: dist/js
   secure: always

 - url: /(.*\.js)$
   mime_type: text/javascript
   static_files: dist/\1
   upload: dist/.*\.js$
   secure: always

 - url: /(.*\.(ico|txt|json))$
   static_files: dist/\1
   upload: dist/.*\.(ico|txt|json)$
   secure: always

 - url: '/(.*)'
   mime_type: text/html
   static_files: dist/index.html
   upload: dist/index.html
   secure: always
   expiration: "0m"